apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: wait-for-db
resources:
- postgres
- pgadmin

images:
  - name: POSTGRES
    newName: docker.io/postgres
    newTag: "14"
