apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: POSTGRES
          env:
            - name: PGHOST
              value: postgres
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
          command:
            - /bin/sh
            - -c
            - |
              while ! psql -c 'select 1' > /dev/null 2>&1; do
                echo "waiting for database"
                sleep 1
              done
              echo "database is ready!"
      containers:
        - image: docker.io/dpage/pgadmin4:snapshot
          name: pgadmin
          envFrom:
            - secretRef:
                name: pgadmin-credentials
          env:
            - name: PGADMIN_DISABLE_POSTFIX
              value: "1"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-data
