apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: pgadmin
resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- ingress.yaml

secretGenerator:
- envs:
  - pgadmin-credentials.env
  name: pgadmin-credentials
