apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: postgres
resources:
- deployment.yaml
- pvc.yaml
- service.yaml

secretGenerator:
- envs:
  - postgres-credentials.env
  name: postgres-credentials
